travis:
  secure:
    BINSTAR_TOKEN: T/pPyky8j6SACJk83PrJUETP497qvIEcnwoVvoMIEBDgOrO38rU2F4KpBrwmjI20STMu1V6eSGCrMlzyn8RBBMBRR3h43llDfcQ2fduYZUy8+aiwL6cfewkthBOwSu4Qp2ICoUeU5Hgg+bDWRZCm+ZCpAZRFLMLWcGMMOp4w27cd+YBVKcgHgmwNBgvZeOokRI3/2c6ZDAbxI1Mgq9aTOy1hTXW+279xIBGPg3uu8CDywtU+7C9G+4ntfl47eooDZMR5C94ZjDNFWWp9ZcQJhj0taVEHXEAJPWm2qy7i2sjII9vMLuduo/79XHGCGPsoqgpKSxFGRWD0LnoBrG7hU8tWfvRpSCP6uDUaMiIztq1LKHKg4w7uooABcRON/vcXiYosaRoCziPzkNbIj3cT2KZelb3Z1ooUQ0yCcol6U31c7riSO13E4O3B03OTedCjkfD9qu+gqY9lzi0D7jxzaGs20BqyV1fl04OWbQHqnxRTz9e6g4Bfm69cwX7+R2f8P971l5DaE2E2HHBlLTL03NaG8nsGt7520K3KEI8yRCvumJOVbELVSMPKlnuk6tnCGnTdGY6QqaPUvVmGp+4V9UbQSF22GQ1yDfShODl3waL0s24Ovu5G/2NUhKAgft9/cVilIYoVPwB4dgMYVHZSatW4/cQuuoGGQYP13JQvGgE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
